# Generated by Django 5.1.6 on 2025-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocmarkt1', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('GB', 'United Kingdom'), ('US', 'United States'), ('FR', 'France'), ('DE', 'Germany'), ('ES', 'Spain'), ('IT', 'Italy'), ('RO', 'Romania'), ('PL', 'Poland'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('DK', 'Denmark'), ('SE', 'Sweden'), ('NO', 'Norway'), ('FI', 'Finland'), ('AT', 'Austria'), ('CH', 'Switzerland')], default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default='GB', max_length=100),
            preserve_default=False,
        ),
    ]
