# Generated by Django 5.1.6 on 2025-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocmarkt1', '0004_alter_order_options_remove_order_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
