# Generated by Django 5.1.6 on 2025-04-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocmarkt1', '0005_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
