# Generated by Django 5.1.6 on 2025-04-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bocmarkt1', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], max_length=10),
        ),
    ]
